# Generated by Django 4.2.30 on 2026-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi (Ruscha)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nomi (O'zbekcha)"),
        ),
    ]
