# Generated by Django 4.2.30 on 2026-05-04 20:04

from django.db import migrations

def seed_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.all().delete()
    
    categories = [
        {'slug': 'blenders', 'name_uz': 'Blenderlar', 'name_ru': 'Блендеры', 'icon': '🫙', 'order': 1},
        {'slug': 'coffee-machines', 'name_uz': 'Kofe mashinalari', 'name_ru': 'Кофемашины', 'icon': '☕', 'order': 2},
        {'slug': 'microwaves', 'name_uz': "Mikroto'lqinli pechlar", 'name_ru': 'Микроволновые печи', 'icon': '📡', 'order': 3},
        {'slug': 'juicers', 'name_uz': 'Sok siqgichlar', 'name_ru': 'Соковыжималки', 'icon': '🍊', 'order': 4},
        {'slug': 'mixers', 'name_uz': 'Mikserlar', 'name_ru': 'Миксеры', 'icon': '🥄', 'order': 5},
        {'slug': 'food-processors', 'name_uz': 'Kombaynlar', 'name_ru': 'Комбайны', 'icon': '⚙️', 'order': 6},
        {'slug': 'electric-kettles', 'name_uz': 'Elektr choynaklar', 'name_ru': 'Электрочайники', 'icon': '🫖', 'order': 7},
        {'slug': 'toasters', 'name_uz': 'Tosterlar', 'name_ru': 'Тостеры', 'icon': '🍞', 'order': 8},
        {'slug': 'air-fryers', 'name_uz': 'Aerogrilllar', 'name_ru': 'Аэрогрили', 'icon': '🌬️', 'order': 9},
        {'slug': 'multicookers', 'name_uz': 'Multivarkalar', 'name_ru': 'Мультиварки', 'icon': '🍲', 'order': 10},
    ]

    for cat in categories:
        Category.objects.create(
            name=cat['name_uz'],
            name_uz=cat['name_uz'],
            name_ru=cat['name_ru'],
            slug=cat['slug'],
            icon=cat['icon'],
            order=cat['order']
        )

def reverse_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_name_ru_category_name_uz'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_categories),
    ]
