# Generated by Django 4.2.30 on 2026-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Ruscha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Tavsif (O'zbekcha)"),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nomi (Ruscha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Nomi (O'zbekcha)"),
        ),
    ]
