# Generated by Django 4.2.30 on 2026-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Xususiyat nomi'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Xususiyat nomi'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Qiymati'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Qiymati'),
        ),
    ]
