# Generated by Django 4.2.30 on 2026-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand_name_ru_brand_name_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Brend'),
        ),
    ]
